version: '3.8'
services:
  db:
    image: mariadb
    container_name: mariadb_symfony_${PROJECT_NAME:-symfony-docker}
    restart: always
    ports:
      - '${MARIADB_PORT:-3306}:3306'
    environment:
      # MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}

  adminer:
    image: adminer
    container_name: adminer_symfony_${PROJECT_NAME:-symfony-docker}
    restart: always
    ports:
        - '${ADMINER_PORT:-8080}:8080'

  web:
    image: nginx
    container_name: nginx_symfony_${PROJECT_NAME:-symfony-docker}
    restart: on-failure
    volumes:
      - ./App/public:/usr/src/app
      - ./Docker-config/nginx/web_server_configuration.conf:/etc/nginx/conf.d/default.conf:ro
      - ./Docker-config/nginx/logs:/var/log/nginx
    ports:
          - '${NGINX_PORT:-80}:80'
    depends_on:
      - php-fpm
      - php-node-cli

  php-node-cli:
    build:
      context: .
      dockerfile: Docker-config/php-node-cli/Dockerfile
    container_name: phpnodecli_symfony_${PROJECT_NAME:-symfony-docker}
    tty: true
    stdin_open: true
    volumes:
    - ./App:/usr/src/app
    - .env:/usr/src/app/.env
    - .env.${APP_ENV}:/usr/src/app/.env.${APP_ENV}

  php-fpm:
    build:
      context: .
      dockerfile: Docker-config/php-fpm/Dockerfile
    container_name: phpfpm_symfony_${PROJECT_NAME:-symfony-docker}
    volumes:
      - .env:/usr/src/app/.env
      - .env.${APP_ENV}:/usr/src/app/.env.${APP_ENV}
      - ./App:/usr/src/app
    restart: on-failure

  node:
    image: node:14-alpine
    container_name: node_symfony_${PROJECT_NAME:-symfony-docker}
    volumes:
      - .env:/usr/src/app/.env
      - .env.${APP_ENV}:/usr/src/app/.env.${APP_ENV}
      - ./App:/usr/src/app
    working_dir: /usr/src/app
    command: yarn --verbose run watch
    restart: on-failure
    depends_on:
      - php-node-cli

  maildev:
    image: maildev/maildev
    container_name: maildev_symfony_${PROJECT_NAME:-symfony-docker}
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "${MAILDEV_PORT:-8081}:80"
    restart: always